### PR TITLE
More wavy stuff + azalea item fix

### PR DESCRIPTION
**Pull request by supsm**
Adds mushrooms, nether plants, dripleaves, wither rose, and lily pads
also fixes azalea item (whoops)
small dripleaf has a bit of misalignment but it is barely noticeable and much less than azalea

couldn't add hanging roots, spore blossom since they moved a bit too much
couldn't add chains because the top appears to move more than the bottom (which doesn't make sense)

### CODE REVIEW

**Comment by spiralhalo** [comment]
Are fungus and mushroom supposed to be wavy? Mushroom are quite stiff.

**Comment by supsm** [comment]
Hmm... they kinda look like grass though  
should I remove it?

**Comment by spiralhalo** [comment]
You need to use your imagination then, or a 3D resource pack.
And yes, I think so.

**Comment by supsm** [comment]
awoo please notice me

**Pull request merged**
